### ISSUE TITLE
Prototype: We need a start

### ISSUE THREAD

**Issue by Tarcadia** [Tarcadia/Telnet-Extend-Lib#1]
As described, this project is aimed to implement a telnet web page, we need a start to it, that
1. we need a name to this project
2. we need to clarify the requirements
3. we need documents to contain these information above

After these main issues finished and documented in the documents, this issue shall be closed. The modification to the documents should be documented in future issues.

**Comment by Tarcadia** [comment]
我觉得可以做这样几层抽象：
1. 网站：抽象我们通过特点地址访问的内容的集合，应当是一组网页组成的集合；
2. 网页：指代某个实际展示在用户面前的内容的集合，应当是元素的集合；
3. 元素：指代一个视觉或功能上的单元；



作为Telnet服务器，本项目应当实现：
1. 管理用户的接入；
2. 管理内容资源；
3. 实现用户对内容的访问，即交互过程；



需求1. 用户接入
*待完善



需求2. 内容管理

2.1 内容的实体
内容的实体应当是网页和元素，
1. 网页是在用户面前展示的内容，其由元素构成，负责表达元素的构成和展示形式，不应当负责元素的内容细节；网页中展示的元素内容应当是元素的实例或者匿名的实例元素；
2. 元素是内容的实体，负责承载元素的内容细节，应当允许承载静态的和动态的元素内容；元素应当可以是独立于网页的，以实现去耦；静态元素指直接的内容，如确定的文本、像素画等；动态的元素是指其可以通过代码实现超过其本身的功能；元素的实例是指在网页中展示的元素；匿名的实例元素是指不做进一步封装而直接由网页承载内容的元素；
3. 我们认为一个元素、一个网页、一个元素的实例、一个匿名的实例元素都是内容实体，我们都需要统一的标识符管理访问；
4. 特别的，我们要定义一种非常特殊的内容，用于交互，名为行为；行为是由元素承载的；

2.2 内容的访问
内容应当有统一的标识符系统地实现访问，如2.1.3所言；
*待完善；



需求3. 交互实现

3.0 交互是什么
交互是获得用户的行为与提供内容与用户的过程，交互应当是统一的抽象的实现的，这是为了：
1. 以确保交互过程对用户是一致的可预测的；
2. 以实现内容外逻辑和内容的去耦；
3. 从而避免需要由元素接管控制权导致的可能的开销和异常问题；

3.1 交互包括了什么
交互包括了将内容渲染为用户可见的形式，提供用户行为的接口，由用户执行行为，响应用户执行的行为；这里我们希望在一般情况下，交互是由一个通用的形式实现的，如3.0所言；为了实现这样的通用形式，我认为我们可以结合内容的统一标识符进行；

3.2 渲染内容
应当有一个渲染器实现由元素、网页等内容实体到最终内容的渲染；最终内容是指展现在用户面前的内容，即，动态内容已经被执行完毕，全部内容在展示时刻是静态的，单一的；考虑到动态内容和对行为的可视化需求的存在，我们应当期望渲染器对这些内容可以增量更新，即，允许对部分内容的更新进行部分重绘；即使会对整个页面进行发送，该重绘也应当避免对整个页面重新渲染；

3.3 行为接口
应当有一套标准的行为接口；
*待完善

3.4 响应行为
应当有一个简单通用快速的行为响应模式；
*待完善

**Comment by Mundanity-fc** [comment]
是否应该抛弃21世纪对于“网页”和“网页对象”的概念？

Telnet访问远程网页，归根到底就是通过telnet访问到远程主机（的某一进程？），此时远程主机上（的进程）所返回的显示在telnet client上的内容可以被描述成一种网页（或记事文本）。
用户通过指令进行的“网页跳转”，实质上不过是远程进程返回的不同文本。基于此，所谓“网页”所显示的内容不应该独立出“网页”概念成为一个子集，而“动态”变化的内容也应该只是适时地返回不同文本，从而产生“动态”的效果。

**Comment by Mundanity-fc** [comment]
> 是否应该抛弃21世纪对于“网页”和“网页对象”的概念？
> 
> Telnet访问远程网页，归根到底就是通过telnet访问到远程主机（的某一进程？），此时远程主机上（的进程）所返回的显示在telnet client上的内容可以被描述成一种网页（或记事文本）。
> 用户通过指令进行的“网页跳转”，实质上不过是远程进程返回的不同文本。基于此，所谓“网页”所显示的内容不应该独立出“网页”概念成为一个子集，而“动态”变化的内容也应该只是适时地返回不同文本，从而产生“动态”的效果。

换言之，对于页面内容的细分应当归并到“页面设计”的范畴，而不是“通讯设计”的范畴。

**Comment by Tarcadia** [comment]
截至目前，我们已经完成了一段初始的开发阶段，在这段阶段里，我们完成了以下的一些工作内容：
1. 验证telnet机制，对协议的部分可能使用的rfc进行了验证；
2. 验证控制台转义字符机制，对大部分控制台转义字符有了处理能力；
3. 设计实现了Shell模块下单个用户的处理流的机制，验证了其可用性；
4. 实现了Shell、Res、User等类，明确了其功能范围；
5. 明确了ResLoader、Draw、等功能性底层接口的目标；

综合以上实现内容，我认为我们可以暂时封存原型的开发，转而对系统进行大规模重构，自顶向下的进行系统构建。

首先，我们要在设计的基本模式上动议
1. 在之前的模式中，我设想并实现的是可视化控制台模式，即，通过可视化元素辅助控制台输入的形式；
2. 肚肚的设想是纯可视化模式，即，根据页面元素进行控制的形式；

对于模式1，数据流动的逻辑在于，由页面（实现的Res类）提供命令列表作为接口（Res.cmds），由Shell接入一个UI作为控制台处理各种输入，并将输入流、指令流、焦点位置等信息传递给页面，由页面自己负责渲染等，将绘制的画面流传递回Shell进行绘制。这套流程繁琐复杂，Res类需要实现输入流和指令流的两个流接口（Res.update()与Res.run()），需要返回一个生成完的流（Res.draw()），且大部分情况下需要在内部再进行部分封装才能实现期望的功能，这是繁琐的。
但该逻辑更符合字符界面下的常用操作逻辑，可以为接入提供更便捷的接口，这是设计时的期望。
其流大致如下：
![图片](https://user-images.githubusercontent.com/47021599/142684698-8a18953d-e1cb-4b69-9b65-53aa05b8bb59.png)

对于模式2，其逻辑类似于HTTP逻辑，由Shell统一管理一个焦点，然后交由焦点所在的各个元素本身进行输入流的处理；由于字符界面下的信息承载量有限，我不认为这里适合进行迭代式的绘制处理，而应当要求页面元素扁平的展开于单层的页面信息上，不应当具有嵌套关系，由页面元素处理各自的输入流后返回轻量的信息，由Shell统一绘制内容。
![图片](https://user-images.githubusercontent.com/47021599/142686548-b1f26f3b-3049-42b6-a4d1-887501e864e7.png)

我认为可以转向模式2，也可考虑将模式2的绘图下至元素本身进行，以需求，以实现为准。对于模式1的控制台化的操作逻辑，我认为可以保留对telnet输入流的接口，允许在输入流上承载某种配置，如linemode开启时使用指令化模式，在指令化模式的情况下，可将元素传递给Shell的元素信息打包传递给用户，实现类似http的访问模式，使得用户开发本地终端成为可能，也可进行绘制，以需求，以实现为准。

**Comment by Tarcadia** [comment]
总结以上，我们现在可以结束该开始章节，接下来我们需要开始对Prototype的大规模重构：
项目的名称转为TEL - Telnet Embedded bLog，一款嵌入于Telnet的BBS/BLOG系统。
该系统的需求是，基于Telnet协议，使用Telnet访问，实现网站信息承载；设计的模式计划采用上文阐述的模式2。
